### ISSUE TITLE
Exporting maps shows toggled overlays

### ISSUE THREAD

**Issue by rezalas** [GrapeshotGames/ServerGridEditor#10]
When exporting maps all overlay data is currently shown in the export, leaving IP, Machine Name, borders, paths, etc. I suggest hiding this info automatically during export and either turning them back on after or just leaving them untoggled to avoid issues. I'll work on a PR that unchecks and restores, let me know if not desired.

**Comment by smooreace** [comment]
What your proposing would be nice... if you don't want those displayed. Some people might want them on, or at least some. And it's hardly complicated to turn them off manually prior to export. If you forget then do it again! Not like it takes more than .1 seconds!

**Comment by GrapeshotGames** [comment]
I wonder if these should even be saved or just used at runtime. Or if there should just be one extra checkbox or option (on export even) that just says 'export display info' which covers all the bases when you want them for debugging. Worth a thought.

**Comment by rezalas** [comment]
I could see a small option when clicking to export all that just verifies display info to show on the generated images. I'll toy around with those ideas tomorrow night when I've got more time.

**Comment by GrapeshotGames** [comment]
I'm going to close this issue for now. Let me know if something comes up in future :)
