### ISSUE TITLE
Setting cell to Freeport or Lawless

### ISSUE THREAD

**Issue by pnkllr** [GrapeshotGames/ServerGridEditor#11]
How does one set each cell to be either lawless or freeport? Cant seem to find a setting for it.

**Comment by smooreace** [comment]
Not the place to ask questions

**Comment by GrapeshotGames** [comment]
You can look at ServerGrid.json for some settings we used to make the concept of a 'lawless'. In particular 'OverrideShooterGameModeDefaultGameIni'. But yes smooreace is right we would like to keep questions focused on the tool itself here. :)
