### ISSUE TITLE
Cant open .exe

### ISSUE THREAD

**Issue by Leebum** [GrapeshotGames/ServerGridEditor#12]
Simply i cannot launch the .exe.
Had no issues with any other .exe and my firewall is not preventing it.

**Comment by rezalas** [comment]
You might download again, I've used this .exe on three other machines without issue. Also since it's a foreign unsigned executable you may receive the "MS suggests not opening..." prompt where you have to click "more info" to unhide the "run anyway" button. Alternatively, you may also have to right click the executable, click properties, and on the general panel uncheck "block executable" in the bottom right corner then select OK.

**Comment by Leebum** [comment]
Awesome timing in response. thank you so much. Sadly after redownloading it 5 times, and selecting run anyway it still wont open.
Also in properties it does not have any option to unblock it.
Lee
________________________________

**Comment by rezalas** [comment]
Did you extract all the files to a folder or are you just downloading the exe?

**Comment by Leebum** [comment]
Well done xD that exactly what i did. i realised that 5 mins after your last email. so far im having trouble getting it to work on my server.

________________________________

**Comment by Leebum** [comment]
That Redis, how do i do that? i rent of a comapny. mine is not dedicated.



________________________________

**Comment by rezalas** [comment]
That, I do not know for your company instance. You would likely need to contact their support department, but that's beyond the scope of the issue you posted for this tool :/ You should check the forums for the unofficial atlas dedicated servers which will have a lot of help with configuring the server properly.

**Comment by Leebum** [comment]
So on my provider there is text doc as part of th configs mentioning Redis and databases. So when i add a map, what do i need to do with database?
Sorry if that question makes no sense.

________________________________

**Comment by scotlynhatt** [comment]
I stood up a new Windows instance to run the ServerGridEditor and was prompted to install .Net Framework. I ended up having to install 4 manually and then the editor asked if I wanted to install 4.5.1 the next time I ran it. Once all of these were updated the editor launched for me. Redis is only necessary before you run the server but you do need to know if it will be using local 127.0.0.1 or some other server IP when you are building the map in this tool. The install via steamcmd brings in a Redis instance if you do not have your own. the 1x1 guide on playatlas.com has all the instructions.

**Comment by GrapeshotGames** [comment]
Correct this does require dotNet 4.5.1 to run. :)  As far as Redis goes more step by step instructions will come in the wiki later but no special requirements are really needed for running Redis.  Included in the game files you can look at AtlasTools/RedisDatabase/redis-server_start.bat for how we can launch it when testing locally. As far as your provider goes I'm not sure what they are doing for that setup there.

**Comment by Leebum** [comment]
Cheers for your help. was very helpful.
One question, using the editor, how do i add a home port like officals where there are npc shops?
ty

________________________________
