### ISSUE TITLE
Map not changing on the game

### ISSUE THREAD

**Issue by Mist3rTrixt3r** [GrapeshotGames/ServerGridEditor#13]
I edited the map, exported the images, uploaded them.  On Atlas, my mini-map shows the images that I uploaded, but the islands are not matching the images. I'm pretty sure I'm missing a step here, but I can't for the life of me figure it out.  I assume there needs to be corresponding code to the images so the game knows what island to put where.

**Comment by smooreace** [comment]
I had the same issue.... wiped the server and created a new ID and it
worked fine. Not sure if it was the wipe, or the ID that solved it.

**Comment by Mist3rTrixt3r** [comment]
This may be a noob question (we're all noobs at atlas) but how do i wipe the server?

**Comment by smooreace** [comment]
Delete the Redis database

\AtlasTools\RedisDatabase\redis_atlasdb.rdb

Delete everything in \ShooterGame\Saved

**Comment by Mist3rTrixt3r** [comment]
Ok got that done.  Now I cannot figure out how to change the server ID.  I'm really sorry to be asking so many questions.  Thank you for your help.

**Comment by smooreace** [comment]
This isnt the place to be asking questions at all!

Open your existing ServerGrid
Click PROJECT
Click CREATE
ignore the warning
Hit CTRL-C and close the window.
Click PROJECT
Click EDIT
Hit CTRL-V
The new randomly generated ID has been put in place.... now export
everything and transfer to your server
