### ISSUE TITLE
Servers are not using the SeamlessIP port numbers and then crash

### ISSUE THREAD

**Issue by Rob-bb** [GrapeshotGames/ServerGridEditor#15]
I have setup my servers to use Query Port of 57550 and game port of 5750 and Seamless port of 27000, but when I monitor the ports being used with a tool like CurrPorts it does not show the Seamless port as being in use.  (this is for the first server, the others using increasing port numbers spaced about 3 numbers apart ie: 57553 etc)

I asked another person to check on their server and it is being used on thiers.  

My server does not show up in the Atlas lists and after a few minutes they crash with no error message.

I am using the small 4 grid example from this repo having changed the IP address and name, adn removed the shipping routes,

I don't know what else to try.

**Comment by smooreace** [comment]
This isnt the place to get help. But you probably never changed the Atlas
Id.

**Comment by Rob-bb** [comment]
@GrapeshotGames   Yes, I have set this up, and set port forwarding etc.  Redis is working, I believe the json files are correct.  I can see traffic on the ports being forwarded in my router, and using wireshark I can see the UDP packets reaching the actual server hardware.  Windows Firewall is turned off.  

No data is reaching the ShooterGame application, based on CurrPorts app, but it does show activity on the redis port  for ShooterGame.  I don't know at this point so I am re-installing windows on the machine (it has no other purpose than to be an atlas server)

As I said before it does not open any ports for the SeamlessData.  Notice in the image no ports 27000+ are open for ShooterGame so I am not sure what is wrong.

![image](https://user-images.githubusercontent.com/3431318/50532561-dc858200-0b7f-11e9-8fe2-2a14c19779cc.png)


Also regarding @smooreace comment on the AtlasID Maybe I am misunderstanding it but is it not important, I thought it was for sorting in the list?  I mean if it were important to be unique how are we to pick a unique ID and be sure it remains Unique?  Any way, I did change it to a random number and did try changing it a few times without any change in status.

**Comment by smooreace** [comment]
I have see numbers ranging from 6 to as many as 10 or 11 digits. While its
true that overlaps COULD happen, its pretty damn rare! As to why... its
just a general assumption I guess, as is everything with running an Atlas
server. Literally nothing is concrete at this point. I HAVE had issues with
map images not changing (exported with server data displayed) until I
changed the server ID. So there is far more to that number than just 'a
number'.

**Comment by Rob-bb** [comment]
That's an interesting find @smooreace.  Any how, it's not my issue, I have tracked it down to a simple sounding yet complex issue.  People on my network can not see my server in the server list, people outside my network can.

**Comment by smooreace** [comment]
Then you have a nat problem in your router

**Comment by GrapeshotGames** [comment]
@Rob-bb Ok so that makes me think of how steam returns browser results to you. I will see about adding back a 'LAN' drop down to Atlas sometime next week or one after that. In the meantime as a work around you can create a .bat or shortcut for people to launch something like "AtlasGame.exe 1.2.3.4:6559" to a home server of yours (ip:port) to have it auto connect to it. Let me know if that works for you as a short term stop gap.

**Comment by Rob-bb** [comment]
@GrapeshotGames thanks for the tip, but I sorted it once I realised it was router problem, needed to read up on masquerading and hairpin nat settings.  

But this raises another question for you, with ark I used to run a link on my web page that would start ARK and connect to my server, but with Atlas it sort of loads up and then gets stuck. with the progress bar frozen after loading PrimalGameData_BP

Cheers, and thanks for your help,

**Comment by Rob-bb** [comment]
It's a link on a web page, how will steam know what app it is =without an app id?  you know href="steam://
