### ISSUE TITLE
Can't change water tiles

### ISSUE THREAD

**Issue by Rob-bb** [GrapeshotGames/ServerGridEditor#24]
When I try to change a water tile it says it can't find the path

![image](https://user-images.githubusercontent.com/3431318/50543602-d061f900-0c41-11e9-92ad-2c6fb1f2f202.png)

**Comment by smooreace** [comment]
Ill second that!

**Comment by wartech0** [comment]
I'll see what I can do!

**Comment by wartech0** [comment]
Fixed the water tile picker and put in a pull request, if you can't wait that long see my fork on my github. https://github.com/wartech0/ServerGridEditor.git

**Comment by Rob-bb** [comment]
@wartech0 I think the other paths do it to, like foreground etc, but  I'm not sure what they are for anyway

**Comment by GrapeshotGames** [comment]
Should be working on the latest now :)
