### ISSUE TITLE
What's the result of making a larger grid?

### ISSUE THREAD

**Issue by qqjp** [GrapeshotGames/ServerGridEditor#25]
For a single player, a larger single grid saves more computer resources than multiple grids. If I make a grid larger than 1400000, such as 8400000, what problems will I encounter in the game?
Will private servers better support individual large grids in the future?

**Comment by smooreace** [comment]
This isnt the place for asking questions

**Comment by wartech0** [comment]
At very large grid sizes floating point precision suffers. Basically its a rounding error, so as you make the grid larger things may be place incorrectly, positions of islands etc might be off. It's just best to avoid it qqjp. I am sure you can get away with a little bit over 1400000 but I wouldn't go crazy.

**Comment by rezalas** [comment]
The requirements for each instance have dropped significantly since the initial release, so running two or more grids really isn't that bad on modern hardware. My testbed is a Ryzen 1600@ 3.6Ghz and even running a 12 grid server my only issue is RAM usage.

**Comment by Rob-bb** [comment]
@rezalas How much ram did it use?

**Comment by rezalas** [comment]
@Rob-bb Each instance uses roughly 2GB RAM, so running a 12 grid server will use around 24GB RAM allocated. That said, I don't think most people will run a 3x4. We were able to comfortably fit all the required islands plus unique elements and build a fairly diverse set on a 3x3 for our main setup, and that includes having an entire server dedicated to the maw. If you want to check out our map you can see it at gaming.cyberblacksmith.com/home/atlas

**Comment by Rob-bb** [comment]
I am seeing 3.5 to 4.5  gb per server, I expect  this to go up once players are on it and building stuff

**Comment by rezalas** [comment]
I haven't seen that on Atlas but I normally see that with Ark so it would make sense. Even on our cluster with 18 mods and some massive castles we're sitting ~7GB for our most heavily populated Ark server. Fortunately, RAM is far cheaper than CPU cores.

**Comment by GrapeshotGames** [comment]
As @wartech0 says floating point error hurts you, it's not even just jitters but some things just breaking down entirely after you get too far out there. 1400000 is a per grid cell size. Having multiple servers lets you expand the world not only by allowing more people to be distributed around but it also resets the number space to be relative.  

You can make grids very big but each cell can be limited by what it can handle. RAM varies just by how much stuff you have in a world. You can have a densely packed small world and have it take up much more just by number of actors in it. Atlas has a lower overall base memory footprint than Ark so you save a few GB there thankfully and less persistent creatures in the world. Yes the more things people build or create in the world the more it will add up over time. On top of this a few things can have to allocate temp larger chunks like saving. So you can see little bursts of 500-1000 MB in larger cases so do try to leave yourself a little overhead for fluctuation.

Not sure if any further questions on this so gonna close this one for now.
