### ISSUE TITLE
Can not remove Map Image URL

### ISSUE THREAD

**Issue by Rob-bb** [GrapeshotGames/ServerGridEditor#30]
Hi, when I remove this URL the editor keeps adding it back.

![image](https://user-images.githubusercontent.com/3431318/50550366-0354cd00-0cd4-11e9-8db6-dea3be6c66f1.png)

**Comment by rezalas** [comment]
Hmm, yeah, as a temp solution you can remove it from the ServerGrid.json manually after you generate it. I'll push a PR shortly that fixes it.

**Comment by GrapeshotGames** [comment]
Should be fixed on latest now! :)
