### ISSUE TITLE
in game map not showing up

### ISSUE THREAD

**Issue by dogdaytona** [GrapeshotGames/ServerGridEditor#33]
my in game map is not showing up and i don't know why same with the treasure maps we currently have everything on a D: drive we are running into that issue and we have tried updating and re exporting

**Comment by ayan4m1** [comment]
Are `MetaWorldURL` and `MapImageURL` both set to `""` in your ServerGrid.json?

**Comment by dogdaytona** [comment]
yes

**Comment by Shmee** [comment]
double check your "seamlessDataPort": is forwarded. It's in ServerGrid.json

**Comment by GrapeshotGames** [comment]
The seamlessDataPort is important when you don't use `MetaWorldURL` .  `MapImageURL` is for the join session listing image. I'm assuming you got this figured out?

**Comment by ayan4m1** [comment]
Do you mind closing this issue if it has been resolved?
