### ISSUE TITLE
Configuring in-game map to show territories

### ISSUE THREAD

**Issue by Psychoboy** [GrapeshotGames/ServerGridEditor#34]
Currently territories do not show up in-game. All map functions work (Cell Images, full map, etc...) except the in-game territory maps from claims.

**Comment by GrapeshotGames** [comment]
Hopefully later today or tomorrow we plan on sharing a AtlasTerritoryMap generator with you guys! It is a simple golang application that can talk to redis and your clients directly to get this data pushed out.

**Comment by GrapeshotGames** [comment]
https://github.com/GrapeshotGames/AtlasTerritoryMap This just went up. Note it might not work well in game currently with non square grids.
