### ISSUE TITLE
 Fatal error! leveltick.cpp:1275

### ISSUE THREAD

**Issue by iDarkEmpire** [GrapeshotGames/ServerGridEditor#35]
every few hours, an error occurs on the server

Fatal error!

VERSION: 8.72 
ShooterGameServer.exe!UWorld::Tick() (0x00007ff660ffe42e) + 14 bytes [h:\yarkupdate\engine\source\runtime\engine\private\leveltick.cpp:1275]
ShooterGameServer.exe!UGameEngine::Tick() (0x00007ff660f9e8d2) + 0 bytes [h:\yarkupdate\engine\source\runtime\engine\private\gameengine.cpp:1174]
ShooterGameServer.exe!FEngineLoop::Tick() (0x00007ff65fb8c4ab) + 0 bytes [h:\yarkupdate\engine\source\runtime\launch\private\launchengineloop.cpp:2443]
ShooterGameServer.exe!GuardedMain() (0x00007ff65fb8708d) + 0 bytes [h:\yarkupdate\engine\source\runtime\launch\private\launch.cpp:140]
ShooterGameServer.exe!GuardedMainWrapper() (0x00007ff65fb870ea) + 5 bytes [h:\yarkupdate\engine\source\runtime\launch\private\windows\launchwindows.cpp:125]
ShooterGameServer.exe!WinMain() (0x00007ff65fb8cd9a) + 17 bytes [h:\yarkupdate\engine\source\runtime\launch\private\windows\launchwindows.cpp:209]
ShooterGameServer.exe!__tmainCRTStartup() (0x00007ff661e526bd) + 21 bytes [f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c:618]
KERNEL32.DLL!UnknownFunction (0x00007fff4df08364) + 0 bytes [UnknownFile:0]
ntdll.dll!UnknownFunction (0x00007fff504be851) + 0 bytes [UnknownFile:0]
ntdll.dll!UnknownFunction (0x00007fff504be851) + 0 bytes [UnknownFile:0]
慌瑳删灥楬慣整⁤捁潴⁲汐祡牥慐湷敔瑳䙟浥污彥彃〲਍慌瑳删浥瑯⁥畆据楴湯䌠楬湥側慬䅹楮慭楴湯਍

**Comment by GrapeshotGames** [comment]
Sorry this is not the place for that. This is for ServerGridEditor only. Please see the forums on https://www.playatlas.com/
