### ISSUE TITLE
Instructions Unclear

### ISSUE THREAD

**Issue by rezalas** [GrapeshotGames/ServerGridEditor#4]
The operational instructions for properly generating ServerGrid data is currently unclear. I have attempted to resolve this as much as time allows via PR #3 , though I may be able to revisit this tomorrow for more detail.

**Comment by rezalas** [comment]
New functionality in the latest patch reduces some of the ambiguity surrounding naming files, especially naming the maps and where to place them.

**Comment by GrapeshotGames** [comment]
More will come on the Wiki in the future. Feel free to add some simple instructions to use on the wiki if you think it will help. We do plan to add more over time just swamped getting core features shored up in game itself. Thanks for your patience!
