### ISSUE TITLE
ServerGridEditor: the spawner islands don't have a freeport

### ISSUE THREAD

**Issue by TheGreenZucchini** [GrapeshotGames/ServerGridEditor#41]
So I placed some of the starter islands and none of them had a Freeport or NPC's, I have tried looking what was different about a island that had a Freeport and the one I placed down I could not find any.

**Comment by TheGreenZucchini** [comment]
I found a solution that worked for me, I put three of the same starter islands in and the Freeport town appeared.

This worked for me.

**Comment by paperrain** [comment]
Creo que esta no es la zona correcta para configuración de servidor.


And check this:
https://www.dropbox.com/sh/mwuulgettgiwl3q/AAAtwpHWWmXpYdT6mr_UTwm6a?dl=0

> FREEPORTS CONFIRMED
> Cay_H_WR_E
> Cay_K_TR_E
> Cay_J_EE_E
> Mnt_A_WU_E
> Mnt_F_ET_E
> Mnt_J_WT_E
> Mnt_L_CH_E
> Mnt_O_CL

**Comment by GrapeshotGames** [comment]
A lot of it just has to do with which maps are loaded and for each island the sublevels in it can contain different things. Glad you got it worked out for now.
