### ISSUE TITLE
Island types

### ISSUE THREAD

**Issue by roptaty** [GrapeshotGames/ServerGridEditor#43]
This is not really an issue with the map editor itself, but more with the different island types. I'm missing information about what type of resources and wild life an island type has.

**Comment by smooreace** [comment]
This isnt a help forum

**Comment by Eggonomicon** [comment]
This may help.
https://docs.google.com/spreadsheets/d/12obzl0cx93rtQhpLlCYO_e0nOyGdSQA_MelZe0AROgQ/edit?usp=sharing

And there is little documentation, so while not a help forum true, asking for better documentation is a request for the Tool provided here.
~Eggo

**Comment by vsalyan** [comment]
> This may help.
> https://docs.google.com/spreadsheets/d/12obzl0cx93rtQhpLlCYO_e0nOyGdSQA_MelZe0AROgQ/edit?usp=sharing
> 
> And there is little documentation, so while not a help forum true, asking for better documentation is a request for the Tool provided here.
> ~Eggo

This is great!  It would be nice to be able to sort it by zone.  Need to switch from using A1 to using A01 so the alphabetical sort works correctly.

Also, the formulas in the first couple columns are off.

**Comment by GrapeshotGames** [comment]
That's cool looking! I don't have any information directly about things like what resources are on what islands. Most of this will be easier to see once the Atlas Dev Kit is released and you can load up an island and see what is referenced on each one. I did however forward this on to someone that does a bunch of that setup to take a look and see if they have anything that we could possibly share out for everyone. But likely it would have to be generated and more will eventually be able to be seen in the Dev Kit. So it might have to just wait till that. No promises but I passed it along all the same. Here is hoping! :)
