### ISSUE TITLE
issue by island editing at finalNPCLevelMultiplier=10

### ISSUE THREAD

**Issue by vioskeran** [GrapeshotGames/ServerGridEditor#44]
Hi I have an error in the island editing, the error at finalNPCLevelMultiplier and instanceTreasureQualityMultiplier, can not be set from 10 to 1.0 . he automatically changes the value to 10 at another island by save.

**Comment by GrapeshotGames** [comment]
This seems working for me. The only thing that comes to mind is the non obvious 'save'. The save on that dialog doesn't actually save the project. You have to go up to `Project -> Save` to save it. That is the only thing that saves your current config as is. :)

**Comment by vioskeran** [comment]
Thx for info :D
