### ISSUE TITLE
Cant load Dowloaded JSON grid file

### ISSUE THREAD

**Issue by sjtheriot** [GrapeshotGames/ServerGridEditor#48]
![capture](https://user-images.githubusercontent.com/46658225/51091274-40967180-174e-11e9-9228-80d4120e19d8.PNG)

see attached file, not sure what todo, just want to edit the current server grids we have. any help appreciated. thx!

**Comment by smooreace** [comment]
Someone edited the json file directly and screwed something up. Not an
editor issue.
