### ISSUE TITLE
Picking Foreground presents issue thinking its selecting a directory?

### ISSUE THREAD

**Issue by PhatNacho** [GrapeshotGames/ServerGridEditor#55]
How do we select a Foreground to create custom graphics for the map?

![image](https://user-images.githubusercontent.com/47160258/51941275-16aaa380-240c-11e9-92c7-78e408dff021.png)

This is the current issue?

**Comment by GrapeshotGames** [comment]
You are correct that definitely looks a bit broken currently! Thanks for the heads up. In the very short term you are always more than welcome to edit the images directly to use in your server.

**Comment by PhatNacho** [comment]
Okay great thankyou, i look forward to this been fixed, dont really want to edit every SlippyImg :(! Done for MapImg and CellImg only for now ;) https://cdn.discordapp.com/attachments/387677976310841355/539957841797185536/MapImg2.jpg

**Comment by GrapeshotGames** [comment]
Cool looking map! I just pushed up a change for this, I tried generating a slippy map with your example image also for sanity (had to change the ratio slightly to cover the 3x3 in my case. Try out and let us know!  https://github.com/GrapeshotGames/ServerGridEditor/commit/534c3a5abcb96eef9ba2af4a5e8e501eaecbd178

**Comment by PhatNacho** [comment]
Yupp working perfect thanks! the res was same as export maybe a upload bug for foreground not sure? or default the ratio from 1.000 to 1.390 to match the 4096 x 4096 export image :)? but thankyou for fixing so quickly!
