### ISSUE TITLE
Cross Platform Compatibility

### ISSUE THREAD

**Issue by rezalas** [GrapeshotGames/ServerGridEditor#7]
In the project forward it references a web version or a C# WPF or other version that may work better for the community. I could adapt this fairly quickly to cross platform on Linux as well going to .Net Core. Would that be acceptable for an improvement?

**Comment by GrapeshotGames** [comment]
It's an interesting thought. Let me see if any of our dependent tools would be affected over the coming days. Definitely not against the thought overall. Sorry for any delay our main concern is getting the game stabilized and issues fixed! Thank you for your patience.

**Comment by rezalas** [comment]
no problem, I'll hold until you're able to revisit and work on other items. Thanks for making the game, the new server layout is pretty awesome and has great potential.

**Comment by GrapeshotGames** [comment]
We are just gonna hold off on this for now since we would have to change up one particular binding that would need reworking in .net core. In a month or two think it can be brought back up as we will be able to move off that then.  :)
