### ISSUE TITLE
Slippy Map waters tile tiling issue

### ISSUE THREAD

**Issue by smooreace** [GrapeshotGames/ServerGridEditor#75]
Has anyone run across this issue before? I can expert all of the normal images without any trouble. The watertire remains scaled at the desired level. But the slippymap seems to be scaling the watertile to whatever is required to give a 4x4 grids. 

This is on a 6x9 map. Watertile is a 24bit, 2731x4096 png file at the same DPI at the stock watertile.
this is the output file in the /0/0/ directory
https://gyazo.com/e5a42aedd1739881eb39e6ee480a68ab

**Comment by antihax** [comment]
Fixed in PR #72 also.

**Comment by smooreace** [comment]
Thank you!
